services:
  - type: web
    name: sonolab-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.free
    healthCheckPath: /api/v1/health
    envVars:
      - key: API_KEY
        sync: false
